### ISSUE TITLE
text overflow on mobile view 

### ISSUE THREAD

**Issue by eraygundogmus** [yavuzyalcintas/AskAnonym#14]
<img width="456" alt="Screen Shot 2023-03-04 at 02 30 20" src="https://user-images.githubusercontent.com/74984741/222854372-97cb1742-7fe5-495c-897c-17833fc6349f.png">

**Comment by Ketcap** [comment]
@eraygundogmus pr acmak ister misin ?

**Comment by eraygundogmus** [comment]
> @eraygundogmus pr acmak ister misin ? 

evet bugün açabilirim
