### ISSUE TITLE
search input empty state

### ISSUE THREAD

**Issue by eraygundogmus** [yavuzyalcintas/AskAnonym#15]
it'd be great if you could add a debounce, spinner and empty state for this logic
<img width="316" alt="Screen Shot 2023-03-04 at 02 31 03" src="https://user-images.githubusercontent.com/74984741/222854441-42f0eb10-d7e3-4543-994b-be62255a15ce.png">

**Comment by ahmetilhn** [comment]
I am working on this issue fyi @eraygundogmus

**Comment by ahmetilhn** [comment]
This issue has been done with PR https://github.com/yavuzyalcintas/AskAnonym/pull/28 @yavuzyalcintas

**Comment by yavuzyalcintas** [comment]
Done
