### ISSUE TITLE
Kullanıcı login olduktan sonra kendi profil bilgilerini düzenleyebilmeli

### ISSUE THREAD

**Issue by resatyildiz** [yavuzyalcintas/AskAnonym#3]
![Ekran Resmi 2023-03-02 17 38 47](https://user-images.githubusercontent.com/30931357/222459478-9e8e6032-0776-4feb-87b7-402c76af828e.png)

new topic butonu yanına edit profile yazan bir buton koyulabilir ve profil bilgilerini düzenleyeceği ekrana yönlendirilebilir.

Bu issue giderildikten sonra user info içerikleri hakkında başka bir issue altında yaklaşım çerçevesi belirlenebilir. @yavuzyalcintas

**Comment by Ketcap** [comment]
@resatyildiz su an upload profile image var, username degismiyor register oldukdan sonra. Degisek tek sey fotograf oda eklendi su commit ile https://github.com/yavuzyalcintas/AskAnonym/commit/3058b51e7958416c68b978c40644092dfd21a96b

Baska fikirlerin varsa gonder gelsin inceleyelim olmadi prida acabilirsin
