### ISSUE TITLE
Fix logo's position

### ISSUE THREAD

**Issue by G-khan** [yavuzyalcintas/AskAnonym#35]
Hey,
The logo does not appear to fit well within the header. It would be better to move it up slightly.

<img width="1274" alt="Screenshot 2023-03-09 at 11 44 44" src="https://user-images.githubusercontent.com/6300144/223968034-ead27213-ff04-4c8f-a2cc-fa0cb9f67ef8.png">

**Comment by yavuzyalcintas** [comment]
It's sitting on the navbar :D

**Comment by G-khan** [comment]
That's not a bug, that's a feature!
