### ISSUE TITLE
Create profile info area and edit profile detail feature

### ISSUE THREAD

**Issue by resatyildiz** [yavuzyalcintas/AskAnonym#36]
We should to create profile info area like is this area.

![localhost_3000_saeros](https://user-images.githubusercontent.com/30931357/224014555-f702fb1a-54ac-4351-b279-76d8ca31a730.png)

**Comment by Ketcap** [comment]
![image](https://user-images.githubusercontent.com/7689820/224254565-147299b5-3074-4ccf-a0d7-c2921f5df7a4.png)
closing because it has been added
