### ISSUE TITLE
Projenin calistirilabilmesi incin Instruction

### ISSUE THREAD

**Issue by microgenius** [yavuzyalcintas/AskAnonym#6]
Projeyi localde ayaga kaldirabilmek icin gerekli olan adimlar readme dosyasina eklenirse katki saglayacak olanlar icin daha tesvik edici olur

**Comment by Ketcap** [comment]
Proje genel olarak calistiriliyor ama env variablelar olmasi lazim @yavuzyalcintas ne diyosun ekleyelim mi envleri

**Comment by yavuzyalcintas** [comment]
env example olarak ekledim

**Comment by yavuzyalcintas** [comment]
Readme güncellemesi de yapılacak
